import type { Employee, Department, SalaryHistory, Branch, PayrollSheet, ReviewRequest } from './types'

export const mockBranches: Branch[] = [
  { id: 'b1', name: 'الفرع الرئيسي', createdAt: new Date() },
  { id: 'b2', name: 'فرع المدينة', createdAt: new Date() },
  { id: 'b3', name: 'فرع الحي الجديد', createdAt: new Date() },
]

export const mockDepartments: Department[] = [
  { id: 'd1', name: 'خدمات', employeeCount: 5, createdAt: new Date() },
  { id: 'd2', name: 'ضيافة', employeeCount: 4, createdAt: new Date() },
  { id: 'd3', name: 'شاورما', employeeCount: 3, createdAt: new Date() },
  { id: 'd4', name: 'كيك', employeeCount: 2, createdAt: new Date() },
  { id: 'd5', name: 'إيطالي', employeeCount: 3, createdAt: new Date() },
  { id: 'd6', name: 'بار', employeeCount: 2, createdAt: new Date() },
  { id: 'd7', name: 'حلويات شرقية', employeeCount: 2, createdAt: new Date() },
  { id: 'd8', name: 'كول سنتر', employeeCount: 3, createdAt: new Date() },
  { id: 'd9', name: 'مصنع', employeeCount: 4, createdAt: new Date() },
  { id: 'd10', name: 'ضبط جودة', employeeCount: 2, createdAt: new Date() },
  { id: 'd11', name: 'كاشيرات', employeeCount: 3, createdAt: new Date() },
  { id: 'd12', name: 'إدارة', employeeCount: 2, createdAt: new Date() },
]

export const mockEmployees: Employee[] = [
  {
    id: '1',
    nationalId: '1234567890',
    fullName: 'أحمد محمد علي',
    phoneNumber: '0501234567',
    password: 'admin123',
    employeeId: 'E20001',
    branchId: 'b1',
    branch: 'الفرع الرئيسي',
    departmentId: 'd12',
    department: 'إدارة',
    workType: 'hourly',
    hourlyRate: 25,
    dailyRate: 200,
    wallet: {
      phoneNumber: '0501234567',
      ownerName: 'أحمد محمد علي',
      ownerId: '1234567890'
    },
    status: 'active',
    role: 'admin',
    baseSalary: 5000,
    workHours: 200,
    withdrawals: 500,
    remaining: 4500,
    paymentStatus: 'bank_transfer',
    cashDays: 3,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    id: '2',
    nationalId: '2345678901',
    fullName: 'سارة أحمد خالد',
    phoneNumber: '0502345678',
    password: 'hr123',
    employeeId: 'E20002',
    branchId: 'b1',
    branch: 'الفرع الرئيسي',
    departmentId: 'd12',
    department: 'إدارة',
    workType: 'hourly',
    hourlyRate: 22,
    dailyRate: 180,
    wallet: {
      phoneNumber: '0502345678',
      ownerName: 'سارة أحمد خالد',
      ownerId: '2345678901'
    },
    status: 'active',
    role: 'hr',
    baseSalary: 4500,
    workHours: 180,
    withdrawals: 200,
    remaining: 4300,
    paymentStatus: 'bank_transfer',
    cashDays: 3,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    id: '3',
    nationalId: '3456789012',
    fullName: 'محمد عبدالله حسن',
    phoneNumber: '0503456789',
    password: '0003',
    employeeId: 'E20003',
    branchId: 'b1',
    branch: 'الفرع الرئيسي',
    departmentId: 'd1',
    department: 'خدمات',
    workType: 'hourly',
    hourlyRate: 15,
    dailyRate: 120,
    wallet: {
      phoneNumber: '0503456789',
      ownerName: 'محمد عبدالله حسن',
      ownerId: '3456789012'
    },
    status: 'active',
    role: 'employee',
    baseSalary: 3000,
    workHours: 220,
    withdrawals: 1000,
    remaining: 2000,
    paymentStatus: 'bank_transfer',
    cashDays: 3,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    id: '4',
    nationalId: '4567890123',
    fullName: 'فاطمة يوسف سعيد',
    phoneNumber: '0504567890',
    password: '0004',
    employeeId: 'E20004',
    branchId: 'b2',
    branch: 'فرع المدينة',
    departmentId: 'd2',
    department: 'ضيافة',
    workType: 'daily',
    hourlyRate: 14,
    dailyRate: 110,
    wallet: {
      phoneNumber: '0504567890',
      ownerName: 'فاطمة يوسف سعيد',
      ownerId: '4567890123'
    },
    status: 'active',
    role: 'employee',
    baseSalary: 2800,
    workHours: 200,
    withdrawals: 2300,
    remaining: 500,
    paymentStatus: 'cash',
    cashDays: 5,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    id: '5',
    nationalId: '5678901234',
    fullName: 'علي حسين محمود',
    phoneNumber: '0505678901',
    password: '0005',
    employeeId: 'E20005',
    branchId: 'b1',
    branch: 'الفرع الرئيسي',
    departmentId: 'd3',
    department: 'شاورما',
    workType: 'hourly',
    hourlyRate: 16,
    dailyRate: 130,
    wallet: {
      phoneNumber: '0505678901',
      ownerName: 'علي حسين محمود',
      ownerId: '5678901234'
    },
    status: 'active',
    role: 'employee',
    baseSalary: 3200,
    workHours: 240,
    withdrawals: 500,
    remaining: 2700,
    paymentStatus: 'bank_transfer',
    cashDays: 3,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    id: '6',
    nationalId: '6789012345',
    fullName: 'نور الدين أحمد',
    phoneNumber: '0506789012',
    password: '0006',
    employeeId: 'E20006',
    branchId: 'b2',
    branch: 'فرع المدينة',
    departmentId: 'd4',
    department: 'كيك',
    workType: 'hourly',
    hourlyRate: 15,
    dailyRate: 120,
    wallet: {
      phoneNumber: '0506789012',
      ownerName: 'نور الدين أحمد',
      ownerId: '6789012345'
    },
    status: 'suspended',
    role: 'employee',
    baseSalary: 2900,
    workHours: 190,
    withdrawals: 800,
    remaining: 2100,
    paymentStatus: 'processing',
    cashDays: 3,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    id: '7',
    nationalId: '7890123456',
    fullName: 'ريم سامي عبدالرحمن',
    phoneNumber: '0507890123',
    password: '0007',
    employeeId: 'E20007',
    branchId: 'b3',
    branch: 'فرع الحي الجديد',
    departmentId: 'd5',
    department: 'إيطالي',
    workType: 'daily',
    hourlyRate: 15,
    dailyRate: 125,
    wallet: {
      phoneNumber: '0507890123',
      ownerName: 'ريم سامي عبدالرحمن',
      ownerId: '7890123456'
    },
    status: 'active',
    role: 'employee',
    baseSalary: 3100,
    workHours: 210,
    withdrawals: 2600,
    remaining: 500,
    paymentStatus: 'cash',
    cashDays: 4,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    id: '8',
    nationalId: '8901234567',
    fullName: 'خالد عمر فؤاد',
    phoneNumber: '0508901234',
    password: '0008',
    employeeId: 'E20008',
    branchId: 'b1',
    branch: 'الفرع الرئيسي',
    departmentId: 'd6',
    department: 'بار',
    workType: 'hourly',
    hourlyRate: 13,
    dailyRate: 105,
    wallet: {
      phoneNumber: '0508901234',
      ownerName: 'خالد عمر فؤاد',
      ownerId: '8901234567'
    },
    status: 'active',
    role: 'employee',
    baseSalary: 2700,
    workHours: 180,
    withdrawals: 300,
    remaining: 2400,
    paymentStatus: 'bank_transfer',
    cashDays: 3,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    id: '9',
    nationalId: '9012345678',
    fullName: 'هدى محمد سليم',
    phoneNumber: '0509012345',
    password: '0009',
    employeeId: 'E20009',
    branchId: 'b2',
    branch: 'فرع المدينة',
    departmentId: 'd7',
    department: 'حلويات شرقية',
    workType: 'hourly',
    hourlyRate: 14,
    dailyRate: 115,
    wallet: {
      phoneNumber: '0509012345',
      ownerName: 'هدى محمد سليم',
      ownerId: '9012345678'
    },
    status: 'active',
    role: 'employee',
    baseSalary: 2850,
    workHours: 195,
    withdrawals: 400,
    remaining: 2450,
    paymentStatus: 'bank_transfer',
    cashDays: 3,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    id: '10',
    nationalId: '0123456789',
    fullName: 'ياسر عادل كريم',
    phoneNumber: '0500123456',
    password: '0010',
    employeeId: 'E20010',
    branchId: 'b3',
    branch: 'فرع الحي الجديد',
    departmentId: 'd8',
    department: 'كول سنتر',
    workType: 'hourly',
    hourlyRate: 13,
    dailyRate: 105,
    wallet: {
      phoneNumber: '0500123456',
      ownerName: 'ياسر عادل كريم',
      ownerId: '0123456789'
    },
    status: 'terminated',
    role: 'employee',
    baseSalary: 2600,
    workHours: 200,
    withdrawals: 2100,
    remaining: 500,
    paymentStatus: 'cash',
    cashDays: 3,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    id: '11',
    nationalId: '1122334455',
    fullName: 'مريم عبدالله ناصر',
    phoneNumber: '0511223344',
    password: '0011',
    employeeId: 'E20011',
    branchId: 'b1',
    branch: 'الفرع الرئيسي',
    departmentId: 'd9',
    department: 'مصنع',
    workType: 'daily',
    hourlyRate: 16,
    dailyRate: 130,
    wallet: {
      phoneNumber: '0511223344',
      ownerName: 'مريم عبدالله ناصر',
      ownerId: '1122334455'
    },
    status: 'active',
    role: 'employee',
    baseSalary: 3300,
    workHours: 230,
    withdrawals: 700,
    remaining: 2600,
    paymentStatus: 'bank_transfer',
    cashDays: 3,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    id: '12',
    nationalId: '2233445566',
    fullName: 'عمر حسن جمال',
    phoneNumber: '0522334455',
    password: '0012',
    employeeId: 'E20012',
    branchId: 'b2',
    branch: 'فرع المدينة',
    departmentId: 'd10',
    department: 'ضبط جودة',
    workType: 'hourly',
    hourlyRate: 17,
    dailyRate: 140,
    wallet: {
      phoneNumber: '0522334455',
      ownerName: 'عمر حسن جمال',
      ownerId: '2233445566'
    },
    status: 'active',
    role: 'employee',
    baseSalary: 3500,
    workHours: 200,
    withdrawals: 500,
    remaining: 3000,
    paymentStatus: 'processing',
    cashDays: 3,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    id: '13',
    nationalId: '3344556677',
    fullName: 'لينا سعد توفيق',
    phoneNumber: '0533445566',
    password: '0013',
    employeeId: 'E20013',
    branchId: 'b3',
    branch: 'فرع الحي الجديد',
    departmentId: 'd11',
    department: 'كاشيرات',
    workType: 'hourly',
    hourlyRate: 12,
    dailyRate: 100,
    wallet: {
      phoneNumber: '0533445566',
      ownerName: 'لينا سعد توفيق',
      ownerId: '3344556677'
    },
    status: 'active',
    role: 'employee',
    baseSalary: 2500,
    workHours: 185,
    withdrawals: 1900,
    remaining: 600,
    paymentStatus: 'cash',
    cashDays: 3,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    id: '14',
    nationalId: '4455667788',
    fullName: 'طارق مصطفى رشيد',
    phoneNumber: '0544556677',
    password: '0014',
    employeeId: 'E20014',
    branchId: 'b1',
    branch: 'الفرع الرئيسي',
    departmentId: 'd1',
    department: 'خدمات',
    workType: 'hourly',
    hourlyRate: 14,
    dailyRate: 115,
    wallet: {
      phoneNumber: '0544556677',
      ownerName: 'طارق مصطفى رشيد',
      ownerId: '4455667788'
    },
    status: 'active',
    role: 'employee',
    baseSalary: 2800,
    workHours: 210,
    withdrawals: 600,
    remaining: 2200,
    paymentStatus: 'bank_transfer',
    cashDays: 3,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    id: '15',
    nationalId: '5566778899',
    fullName: 'دينا أحمد فايز',
    phoneNumber: '0555667788',
    password: '0015',
    employeeId: 'E20015',
    branchId: 'b2',
    branch: 'فرع المدينة',
    departmentId: 'd2',
    department: 'ضيافة',
    workType: 'daily',
    hourlyRate: 14,
    dailyRate: 110,
    wallet: {
      phoneNumber: '0555667788',
      ownerName: 'دينا أحمد فايز',
      ownerId: '5566778899'
    },
    status: 'active',
    role: 'employee',
    baseSalary: 2750,
    workHours: 190,
    withdrawals: 400,
    remaining: 2350,
    paymentStatus: 'bank_transfer',
    cashDays: 3,
    createdAt: new Date(),
    updatedAt: new Date()
  }
]

export const mockSalaryHistory: SalaryHistory[] = [
  {
    id: 'sh1',
    employeeId: 'E20003',
    month: 'يناير',
    year: 2024,
    baseSalary: 3000,
    workHours: 200,
    withdrawals: 500,
    remaining: 2500,
    paymentStatus: 'bank_transfer',
    paidAt: new Date('2024-01-28'),
    createdAt: new Date('2024-01-01')
  },
  {
    id: 'sh2',
    employeeId: 'E20003',
    month: 'فبراير',
    year: 2024,
    baseSalary: 3000,
    workHours: 180,
    withdrawals: 800,
    remaining: 2200,
    paymentStatus: 'bank_transfer',
    paidAt: new Date('2024-02-28'),
    createdAt: new Date('2024-02-01')
  },
  {
    id: 'sh3',
    employeeId: 'E20003',
    month: 'مارس',
    year: 2024,
    baseSalary: 3000,
    workHours: 220,
    withdrawals: 1000,
    remaining: 2000,
    paymentStatus: 'bank_transfer',
    paidAt: new Date('2024-03-28'),
    createdAt: new Date('2024-03-01')
  }
]

export const mockPayrollSheets: PayrollSheet[] = [
  {
    id: 'ps1',
    month: 4,
    year: 2026,
    status: 'approved',
    entries: [
      {
        id: 'pe1',
        employeeId: 'E20003',
        employeeName: 'محمد عبدالله حسن',
        employeeNumber: 'E20003',
        department: 'خدمات',
        branch: 'الفرع الرئيسي',
        workType: 'hourly',
        hoursOrDays: 200,
        rate: 15,
        grossSalary: 3000,
        withdrawals: 800,
        netSalary: 2200,
        cashReceived: 500,
        transferReceived: 1500,
        remaining: 200,
        notes: ''
      },
      {
        id: 'pe2',
        employeeId: 'E20004',
        employeeName: 'فاطمة يوسف سعيد',
        employeeNumber: 'E20004',
        department: 'ضيافة',
        branch: 'فرع المدينة',
        workType: 'daily',
        hoursOrDays: 25,
        rate: 110,
        grossSalary: 2750,
        withdrawals: 600,
        netSalary: 2150,
        cashReceived: 2150,
        transferReceived: 0,
        remaining: 0,
        notes: ''
      },
      {
        id: 'pe3',
        employeeId: 'E20005',
        employeeName: 'علي حسين محمود',
        employeeNumber: 'E20005',
        department: 'شاورما',
        branch: 'الفرع الرئيسي',
        workType: 'hourly',
        hoursOrDays: 210,
        rate: 16,
        grossSalary: 3360,
        withdrawals: 500,
        netSalary: 2860,
        cashReceived: 0,
        transferReceived: 2860,
        remaining: 0,
        notes: ''
      }
    ],
    totalGrossSalary: 9110,
    totalWithdrawals: 1900,
    totalNetSalary: 7210,
    totalCashReceived: 2650,
    totalTransferReceived: 4360,
    totalRemaining: 200,
    createdAt: new Date('2026-04-01'),
    approvedAt: new Date('2026-04-28'),
    closedAt: null,
    createdBy: 'admin'
  },
  {
    id: 'ps0',
    month: 3,
    year: 2026,
    status: 'closed',
    entries: [
      {
        id: 'pe4',
        employeeId: 'E20003',
        employeeName: 'محمد عبدالله حسن',
        employeeNumber: 'E20003',
        department: 'خدمات',
        branch: 'الفرع الرئيسي',
        workType: 'hourly',
        hoursOrDays: 185,
        rate: 15,
        grossSalary: 2775,
        withdrawals: 500,
        netSalary: 2275,
        cashReceived: 300,
        transferReceived: 1975,
        remaining: 0,
        notes: ''
      },
      {
        id: 'pe5',
        employeeId: 'E20004',
        employeeName: 'فاطمة يوسف سعيد',
        employeeNumber: 'E20004',
        department: 'ضيافة',
        branch: 'فرع المدينة',
        workType: 'daily',
        hoursOrDays: 22,
        rate: 110,
        grossSalary: 2420,
        withdrawals: 400,
        netSalary: 2020,
        cashReceived: 2020,
        transferReceived: 0,
        remaining: 0,
        notes: ''
      },
      {
        id: 'pe6',
        employeeId: 'E20005',
        employeeName: 'علي حسين محمود',
        employeeNumber: 'E20005',
        department: 'شاورما',
        branch: 'الفرع الرئيسي',
        workType: 'hourly',
        hoursOrDays: 195,
        rate: 16,
        grossSalary: 3120,
        withdrawals: 700,
        netSalary: 2420,
        cashReceived: 0,
        transferReceived: 2420,
        remaining: 0,
        notes: ''
      }
    ],
    totalGrossSalary: 8315,
    totalWithdrawals: 1600,
    totalNetSalary: 6715,
    totalCashReceived: 2320,
    totalTransferReceived: 4395,
    totalRemaining: 0,
    createdAt: new Date('2026-03-01'),
    approvedAt: new Date('2026-03-28'),
    closedAt: new Date('2026-03-30'),
    createdBy: 'admin'
  },
  {
    id: 'ps2',
    month: 5,
    year: 2026,
    status: 'draft',
    entries: [],
    totalGrossSalary: 0,
    totalWithdrawals: 0,
    totalNetSalary: 0,
    totalCashReceived: 0,
    totalTransferReceived: 0,
    totalRemaining: 0,
    createdAt: new Date('2026-05-01'),
    approvedAt: null,
    closedAt: null,
    createdBy: 'admin'
  }
]

export const mockReviewRequests: ReviewRequest[] = [
  {
    id: 'rr1',
    employeeId: 'E20003',
    employeeName: 'محمد عبدالله حسن',
    employeeNumber: 'E20003',
    payrollSheetId: 'ps1',
    month: 4,
    year: 2026,
    reason: 'يوجد خطأ في حساب ساعات العمل الإضافية',
    status: 'pending',
    adminResponse: null,
    createdAt: new Date('2026-04-25'),
    updatedAt: new Date('2026-04-25')
  },
  {
    id: 'rr2',
    employeeId: 'E20005',
    employeeName: 'علي حسين محمود',
    employeeNumber: 'E20005',
    payrollSheetId: 'ps1',
    month: 4,
    year: 2026,
    reason: 'السحوبات المسجلة أكثر من الفعلية',
    status: 'approved',
    adminResponse: 'تم مراجعة السحوبات وتصحيحها',
    createdAt: new Date('2026-04-20'),
    updatedAt: new Date('2026-04-22')
  },
  {
    id: 'rr3',
    employeeId: 'E20007',
    employeeName: 'ريم سامي عبدالرحمن',
    employeeNumber: 'E20007',
    payrollSheetId: 'ps1',
    month: 4,
    year: 2026,
    reason: 'لم يتم احتساب يومين عمل',
    status: 'rejected',
    adminResponse: 'تم التأكد من الحضور وهو مطابق للمسجل',
    createdAt: new Date('2026-04-18'),
    updatedAt: new Date('2026-04-19')
  }
]
